### ISSUE TITLE
ACM 등록 후 오류

### ISSUE THREAD

**Issue by nara1111** [cmsong-shina/sihas-canary#10]
안녕하세요, ACM 등록후 다음의 오류가 나며 상태가 제대로 올라오지 않습니다.

IndexError: list index out of range
2023-07-09 07:20:50.393 INFO (SyncWorker_4) [custom_components.xiaomi_miot.core.miio2miot] zhimi.fan.v3: Got miio props for miot: {'power': 'off', 'speed_level': 74, 'angle_enable': 'off', 'angle': 60, 'natural_level': 1, 'child_lock': 'off', 'battery': 100, 'bat_charge': 'complete'}
2023-07-09 07:20:54.514 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.acma8_2b_d6_36_c2_62 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sihas/climate.py", line 358, in update
    self._attr_fan_mode = Acm300.FAN_TABLE[regs[Acm300.REG_FAN]]
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^

**Comment by cmsong-shina** [comment]
v1.4.1로 업데이트 해보시겠어요?

**Comment by nara1111** [comment]
별도 1.4.1 브랜치는 없는듯 하여, main 브랜치로 업데이트하였습니다.
동일한 문제가 발생하는 것으로 보입니다.

2023-07-10 12:37:52.756 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.acma8_2b_d6_36_c2_62 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sihas/climate.py", line 359, in update
    self._attr_fan_mode = Acm300.FAN_TABLE[regs[Acm300.REG_FAN]]
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2023-07-10 12:37:57.849 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.acma8_2b_d6_36_c2_62 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sihas/climate.py", line 359, in update
    self._attr_fan_mode = Acm300.FAN_TABLE[regs[Acm300.REG_FAN]]
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^

**Comment by cmsong-shina** [comment]
v1.4.2로 올렸습니다.

**Comment by nara1111** [comment]
안녕하세요, 답이 늦었습니다. 1.4.2에서 정상작동합니다.
그런데 온오프 스위치는 현재 컴포넌트에서 지원을 안 하나요?

**Comment by cmsong-shina** [comment]
> 안녕하세요, 답이 늦었습니다. 1.4.2에서 정상작동합니다. 그런데 온오프 스위치는 현재 컴포넌트에서 지원을 안 하나요?

사용자 지정 리모컨 기능 말씀이신가요?
